apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-build
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.30.0
      script: |
        set -e
        cd $(workspaces.source.path)
        buildah bud -t $(params.IMAGE) .
        buildah push $(params.IMAGE)
