apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-k8s
spec:
  params:
    - name: manifest
      type: string
  workspaces:
    - name: source
  steps:
    - name: apply
      image: bitnami/kubectl
      script: |
        kubectl apply -f $(workspaces.source.path)/$(params.manifest)

