apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: fraudshield-template
spec:
  params:
    - name: repo-url
    - name: revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: fraudshield-ci-
      spec:
        pipelineRef:
          name: fraudshield-ci-pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              metadata:
                name: fraudshield-ws
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: revision
            value: $(tt.params.revision)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: fraudshield-binding
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.ref)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: fraudshield-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: fraudshield-trigger
      bindings:
        - ref: fraudshield-binding
      template:
        ref: fraudshield-template

