apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
  labels:
    app: ml-pipeline-ui
spec:
  selector:
    app: ml-pipeline-ui
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

