apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline
  namespace: kubeflow
  labels:
    app: ml-pipeline
spec:
  selector:
    app: ml-pipeline
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP

